import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const REPO = "grizzly020503/swsi-quiz-backup";
const REPO_ID = 1345053575;
const ALLOWED_FIELDS = new Set([
  "id","major","topic","keywords","exp_why","exp_others","exp_trap",
  "exp_raw","mnemonic","extension","law","mistake"
]);
const MISTAKES = new Set([
  "概念混淆","法規混淆","理論人物混淆","流程順序錯誤",
  "計算邏輯錯誤","關鍵字漏看","題幹誤讀"
]);
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function assert(cond:unknown,message:string):asserts cond{if(!cond)throw new Error(message)}
function cleanText(v:unknown,max:number,field:string,allowEmpty=false){assert(typeof v==="string",`${field} 必須是字串`);const s=v.trim();if(!allowEmpty)assert(s.length>0,`${field} 不可空白`);assert(s.length<=max,`${field} 太長`);return s}
async function verifyGitHubRepoWriteToken(token:string){const r=await fetch(`https://api.github.com/repos/${REPO}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"swsi-analysis-updater/1.1"}});if(!r.ok)return false;const repo=await r.json();return Number(repo?.id)===REPO_ID&&repo?.permissions?.push===true}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"POST only"},405);const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"缺少 GitHub Actions token"},401);if(!(await verifyGitHubRepoWriteToken(token)))return json({error:"GitHub token lacks write access to the SWSI repository"},403);let body:any;try{body=await req.json()}catch{return json({error:"無效 JSON"},400)}try{assert(body&&typeof body==="object","payload 必須是 object");assert(/^\d{3}(030|100)$/.test(String(body.exam_code||"")),"exam_code 不符");assert(Array.isArray(body.rows)&&body.rows.length>=1&&body.rows.length<=50,"rows 必須為 1~50 筆");const normalized:any[]=[],ids=new Set<string>();for(const row of body.rows){assert(row&&typeof row==="object"&&!Array.isArray(row),"每筆解析必須是 object");for(const k of Object.keys(row))assert(ALLOWED_FIELDS.has(k),`禁止更新欄位：${k}`);const id=cleanText(row.id,120,"id");assert(!ids.has(id),`重複 id：${id}`);ids.add(id);const mistake=cleanText(row.mistake,40,`${id}.mistake`);assert(MISTAKES.has(mistake),`${id}.mistake 不在既有分類內`);normalized.push({id,major:cleanText(row.major,120,`${id}.major`),topic:cleanText(row.topic,240,`${id}.topic`),keywords:cleanText(row.keywords,500,`${id}.keywords`),exp_why:cleanText(row.exp_why,1800,`${id}.exp_why`),exp_others:cleanText(row.exp_others,1800,`${id}.exp_others`),exp_trap:cleanText(row.exp_trap,1200,`${id}.exp_trap`),exp_raw:null,mnemonic:cleanText(row.mnemonic,1200,`${id}.mnemonic`),extension:cleanText(row.extension,1200,`${id}.extension`),law:cleanText(row.law??"",1200,`${id}.law`,true),mistake,analysis_status:"ready"})}const url=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRole)return json({error:"Supabase server env missing"},500);const sb=createClient(url,serviceRole,{auth:{persistSession:false}});const idList=normalized.map(r=>r.id),{data:existing,error:readError}=await sb.from("questions").select("id,source_exam_code,analysis_status").in("id",idList);if(readError)throw new Error(`questions read: ${readError.message}`);assert((existing||[]).length===normalized.length,"部分題目 ID 不存在，拒絕更新");const existingMap=new Map((existing||[]).map((r:any)=>[r.id,r]));for(const row of normalized){const old:any=existingMap.get(row.id);assert(old?.source_exam_code===body.exam_code,`${row.id} 不屬於 exam_code ${body.exam_code}`)}for(const row of normalized){const{id,...patch}=row;const{error}=await sb.from("questions").update(patch).eq("id",id).eq("source_exam_code",body.exam_code);if(error)throw new Error(`${id} update: ${error.message}`)}return json({ok:true,exam_code:body.exam_code,updated:normalized.length})}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}});
