import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const AI_PROXY_URL = "https://wandering-wave-4418.c022050333.workers.dev";
const DRAFT_MODEL = "qwen/qwen3.6-27b";
const AUDIT_MODEL = "openai/gpt-oss-120b";
const FORMAT_ARTIFACT_TOKENS = new Set(["na","nb","nc","nd"]);
const MISTAKES = new Set(["概念混淆","法規混淆","理論人物混淆","流程順序錯誤","計算邏輯錯誤","關鍵字漏看","題幹誤讀"]);
const MAJORS: Record<string,string[]> = {
  "人類行為與社會環境": ["各年齡發展","家庭與社會","發展理論","社區與文化","社會環境系統","心理健康與偏差","人格與情緒","危機與壓力","生理與遺傳","社會化與社會角色","認知與語言","團體與組織"],
  "社會工作": ["社會工作專業","社會工作倫理","社會工作理論","處遇模式","工作技巧","兒少服務","心理健康","老人服務","障礙者服務","性別與婦女服務","多元文化能力","社區工作","社工管理"],
  "社會工作直接服務": ["社區工作","團體工作","處遇模式與理論","評估與處遇計畫","社會工作倫理","個案工作","會談與溝通技巧","專業關係","紀錄與評鑑","社工角色","結案與追蹤","個案管理"],
  "社會工作研究方法": ["資料蒐集","質性方法","研究邏輯","抽樣","研究設計","測量","統計檢定","信效度","研究方法類型","研究倫理","變項","因果關係","資料分析","內容分析","方案評估","縱貫研究","研究典範","推論謬誤","文獻回顧"],
  "社會政策與社會立法": ["其他社會立法與人權公約","社會政策概念與原則","兒少福利法規","社會保險","身心障礙福利法規","福利意識形態與理論","社會救助","老人福利法規","社會政策過程與決策","婦女與性別法規","社會津貼與福利服務","福利國家與體制"]
};
const FIELDS = ["id","major","topic","keywords","exp_why","exp_others","exp_trap","mnemonic","extension","law","mistake"];
function json(body: unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function clean(v:unknown){return String(v??"").trim()}
function delay(ms:number){return new Promise(r=>setTimeout(r,ms))}
function task(q:any){return{id:q.id,subject:q.subject,question:q.question,A:q.opt_a,B:q.opt_b,C:q.opt_c,D:q.opt_d,official_answer:q.answer}}
function stripJsonFence(text:string){let s=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");if(s.startsWith("[")&&s.endsWith("]"))return s;const a=s.indexOf("["),b=s.lastIndexOf("]");if(a>=0&&b>a)return s.slice(a,b+1);throw new Error("AI 回傳找不到 JSON array")}
function initialPrompt(q:any){return `你是台灣社會工作師國家考試選擇題解析器。官方答案已確定。\n硬性規則：\n1. 不可修改或質疑官方題目、選項、答案，只寫解析。\n2. major 只能從：${JSON.stringify(MAJORS[q.subject]||[])}\n3. mistake 只能從：${JSON.stringify([...MISTAKES])}\n4. topic 用「主題 > 細目」；keywords 用半形逗號分隔。\n5. exp_why 說明正解；exp_others 逐一說明其他選項錯在哪；exp_trap 點考場陷阱。\n6. 正解理由優先只用題幹/選項已提供的核心特徵。禁止新增題面未出現的人名、機構名、英文專名/縮寫、任何阿拉伯數字、年齡、年份、金額、天數、比例或法條號碼。\n7. 若錯誤選項是數值/期限/比例錯誤，而題面沒有提供正確數值，只說「與正確規定不符」，不要自行補正確數字。\n8. mnemonic 短而可記；extension 只寫相鄰考點名稱/比較方向，不補背景故事。\n9. law 只寫確定的法規名稱/原則；非法律題可空白。\n10. 繁體中文、簡潔。只輸出 JSON array；物件只能有 ${JSON.stringify(FIELDS)}。\n題目：${JSON.stringify(task(q))}`}
function auditPrompt(q:any,draft:any){return `你是社會工作師國考題庫最終審稿員。官方答案固定不可改。直接輸出校正後 JSON array。\n1. exp_why 必須支持官方正解；優先使用題面已有的判斷特徵，不新增發展年齡、形成時點或額外背景。\n2. exp_others 每個錯誤選項都要真的指出錯誤，不可先說錯、後面又把同一敘述當真。\n3. 刪除不必要的人物、機構、年代、英文名稱、背景故事、條號與數值。\n4. 禁止新增題面沒有的人名、機構名、英文專名/縮寫、任何阿拉伯數字、年齡、年份、金額、天數、比例或法條號碼。若草稿有，一律刪除。\n5. 數值型錯誤若題面沒有正確數值，只說與正確規定/概念不符，不補數字。\n6. major 只能從 ${JSON.stringify(MAJORS[q.subject]||[])}；mistake 只能從 ${JSON.stringify([...MISTAKES])}。\n7. extension 只寫考點名稱/比較方向；law 不確定就空白。\n8. 只輸出 JSON array；物件只能有 ${JSON.stringify(FIELDS)}。\n官方題目：${JSON.stringify(task(q))}\n草稿：${JSON.stringify(draft)}`}
async function callModel(model:string,prompt:string,reasoning:string,maxTokens:number){const body:any={model,temperature:0,max_tokens:maxTokens,messages:[{role:"user",content:prompt}]};if(reasoning)body.reasoning_effort=reasoning;let last="";for(let attempt=0;attempt<4;attempt++){const r=await fetch(AI_PROXY_URL,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const text=await r.text();if(r.status===429){last=`AI ${model} HTTP 429: ${text.slice(0,300)}`;const hs=Number(r.headers.get("retry-after")||0),m=text.match(/try again in\s+([0-9.]+)s/i),ms=m?Number(m[1]):0,w=Math.max(5,Math.min(35,hs||ms||8));if(attempt<3){await delay((w+1)*1000);continue}throw new Error(last)}if(!r.ok)throw new Error(`AI ${model} HTTP ${r.status}: ${text.slice(0,300)}`);const data:any=JSON.parse(text),content=data?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error(`AI ${model} response shape invalid`);return JSON.parse(stripJsonFence(content))}throw new Error(last||`AI ${model} failed`)}
function asciiTokens(s:string){return new Set((s.match(/[A-Za-z][A-Za-z0-9'’-]*/g)||[]).map(x=>x.toLowerCase()))}
function numberTokens(s:string){return new Set(s.match(/\d+(?:[.,]\d+)?/g)||[])}
function setDiff(a:Set<string>,b:Set<string>){return[...a].filter(x=>!b.has(x))}
function validateFinal(q:any,rows:any){if(!Array.isArray(rows)||rows.length!==1)throw new Error("AI 最終筆數不是 1");const row=rows[0];if(!row||typeof row!=="object"||Array.isArray(row))throw new Error("AI 最終格式不是 object");const keys=Object.keys(row).sort(),expected=[...FIELDS].sort();if(JSON.stringify(keys)!==JSON.stringify(expected))throw new Error(`AI 欄位不符: ${keys.join(',')}`);if(clean(row.id)!==clean(q.id))throw new Error("AI id 不符");if(!(MAJORS[q.subject]||[]).includes(clean(row.major)))throw new Error(`major 不在既有分類: ${row.major}`);if(!MISTAKES.has(clean(row.mistake)))throw new Error(`mistake 不在既有分類: ${row.mistake}`);for(const k of FIELDS){if(k!=="law"&&!clean(row[k]))throw new Error(`${k} 空白`)}const source=`A B C D ${clean(q.question)} ${clean(q.opt_a)} ${clean(q.opt_b)} ${clean(q.opt_c)} ${clean(q.opt_d)} ${clean(q.answer)}`,output=FIELDS.filter(k=>k!=="id").map(k=>clean(row[k])).join(" ");const extraAscii=setDiff(asciiTokens(output),asciiTokens(source)).filter(x=>!FORMAT_ARTIFACT_TOKENS.has(x));if(extraAscii.length)throw new Error(`新增題面沒有的英文詞: ${extraAscii.join(',')}`);const extraNums=setDiff(numberTokens(output),numberTokens(source));if(extraNums.length)throw new Error(`新增題面沒有的數字: ${extraNums.join(',')}`);return{major:clean(row.major),topic:clean(row.topic),keywords:clean(row.keywords),exp_why:clean(row.exp_why),exp_others:clean(row.exp_others),exp_trap:clean(row.exp_trap),exp_raw:null,mnemonic:clean(row.mnemonic),extension:clean(row.extension),law:clean(row.law),mistake:clean(row.mistake),analysis_status:"ready",analysis_attempts:0,analysis_error:null,analysis_started_at:null}}
async function analyzeOne(q:any){const draftRows=await callModel(DRAFT_MODEL,initialPrompt(q),"none",1400);if(!Array.isArray(draftRows)||draftRows.length!==1)throw new Error("草稿格式異常");const finalRows=await callModel(AUDIT_MODEL,auditPrompt(q,draftRows[0]),"medium",1500);return validateFinal(q,finalRows)}
function isTransient(msg:string){return/HTTP 429|rate limit|fetch failed|network|timed?\s*out|temporar/i.test(msg)}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"POST only"},405);const url=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRole)return json({error:"Supabase server env missing"},500);const sb=createClient(url,serviceRole,{auth:{persistSession:false}});const supplied=req.headers.get("x-job-key")||"";const{data:cfg,error:cfgErr}=await sb.from("ai_analysis_job_config").select("job_key,enabled").eq("id",true).maybeSingle();if(cfgErr||!cfg?.enabled||!supplied||supplied!==cfg.job_key)return json({error:"unauthorized job"},403);let body:any={};try{body=await req.json()}catch{}const limit=Math.max(1,Math.min(Number(body?.limit||1),3));const{data:claimed,error:claimErr}=await sb.rpc("claim_pending_ai_questions",{p_limit:limit});if(claimErr)return json({error:`claim: ${claimErr.message}`},500);const rows:any[]=claimed||[],results:any[]=[];for(const q of rows){try{const patch=await analyzeOne(q);const{error}=await sb.from("questions").update(patch).eq("id",q.id).eq("source_exam_code",q.source_exam_code);if(error)throw new Error(`update: ${error.message}`);results.push({id:q.id,status:"ready"})}catch(e){const msg=(e instanceof Error?e.message:String(e)).slice(0,1000),transient=isTransient(msg),attempts=transient?Number(q.analysis_attempts||0):Number(q.analysis_attempts||0)+1,status=transient?"pending":attempts>=3?"review":"pending";await sb.from("questions").update({analysis_status:status,analysis_attempts:attempts,analysis_error:msg,analysis_started_at:null}).eq("id",q.id);results.push({id:q.id,status,error:msg,attempts,transient})}}const{count:pending}=await sb.from("questions").select("id",{count:"exact",head:true}).eq("analysis_status","pending"),{count:review}=await sb.from("questions").select("id",{count:"exact",head:true}).eq("analysis_status","review");return json({ok:true,claimed:rows.length,results,pending,review})});
