create table public.swsi_feedback_reports (
  id uuid primary key default gen_random_uuid(),
  report_no bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending','reviewed','fixed','no_change')),
  category text not null check (category in ('question_display','answer_question','explanation_error','law_outdated','theory_question','site_bug','ai_feedback','suggestion','other')),
  context_type text not null default 'general' check (context_type in ('mcq','essay','theory','law','general')),
  context_id text,
  context_title text,
  source_kind text not null default 'swsi' check (source_kind in ('official_exam','swsi','ai','unknown')),
  subject text,
  exam_year integer,
  exam_round integer,
  question_no integer,
  message text not null check (char_length(message) between 3 and 2000),
  contact text check (contact is null or char_length(contact) <= 200),
  page_path text check (page_path is null or char_length(page_path) <= 500),
  site_origin text check (site_origin is null or char_length(site_origin) <= 200),
  app_version text check (app_version is null or char_length(app_version) <= 120),
  user_agent text check (user_agent is null or char_length(user_agent) <= 500),
  client_hash text not null,
  metadata jsonb not null default '{}'::jsonb,
  reviewer_note text,
  resolved_at timestamptz
);

create index swsi_feedback_reports_status_created_idx
  on public.swsi_feedback_reports(status, created_at desc);
create index swsi_feedback_reports_client_created_idx
  on public.swsi_feedback_reports(client_hash, created_at desc);
create index swsi_feedback_reports_context_idx
  on public.swsi_feedback_reports(context_type, context_id);

alter table public.swsi_feedback_reports enable row level security;
revoke all on table public.swsi_feedback_reports from anon, authenticated;
revoke all on sequence public.swsi_feedback_reports_report_no_seq from anon, authenticated;

create or replace function public.swsi_feedback_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  if new.status in ('fixed','no_change') and old.status is distinct from new.status and new.resolved_at is null then
    new.resolved_at = now();
  elsif new.status not in ('fixed','no_change') then
    new.resolved_at = null;
  end if;
  return new;
end;
$$;

create trigger swsi_feedback_touch_updated_at
before update on public.swsi_feedback_reports
for each row execute function public.swsi_feedback_touch_updated_at();

comment on table public.swsi_feedback_reports is 'SWSI public quality reports submitted through the protected Edge Function. No direct anon/authenticated access.';
comment on column public.swsi_feedback_reports.client_hash is 'SHA-256 hash of the existing random SWSI client identifier; used only for anti-spam rate limiting.';
